@startuml Diagramme de cas d'utilisation
left to right direction

actor Utilisateur as user

package EasySave {
  usecase "Créer une sauvegarde" as uc1
  usecase "Renseigner Nom" as uc7
  usecase "Renseigner répertoire source" as uc8
  usecase "Renseigner répertoire cible" as uc9
  usecase "Renseigner type de sauvegarde" as uc10
  usecase "Quitter l'application" as uc6
  usecase "Lancer une sauvegarde" as uc2
  usecase "Sélectionner la sauvegarde" as uc3
  usecase "Remplir le fichier journalier de logs" as uc4
  usecase "Remplir le fichier d'état en temps réel" as uc5
  usecase "Sélection de la langue" as uc11
}

user --> uc1
user --> uc11
uc1 --> uc7
uc1 --> uc8
uc1 --> uc9 
uc1 --> uc10
user --> uc6
user --> uc2
uc2 --> uc3
uc2 .-> uc4 : <<include>>
uc2 .-> uc5 : <<include>>
@enduml