@startuml Diagramme de cas d'utilisation
left to right direction

actor Utilisateur as user

package EasySave {
    usecase "Lancer un / plusieurs travaux de sauvegarde(s)" as UC_Lancer
    usecase "Ajouter un travail de sauvegarde" as UC_Creer
    usecase "Modifier un travail de sauvegarde" as UC_Modifier
    usecase "Supprimer un travail de sauvegarde" as UC_Supprimer
    usecase "Afficher les travaux de sauvegarde" as UC_Afficher
    usecase "Afficher l'aide" as UC_Aide
    usecase "Modifier la langue de l'application" as UC_Langue
}

user --> UC_Lancer
user --> UC_Creer
user --> UC_Modifier
user --> UC_Supprimer
user --> UC_Afficher
user --> UC_Aide
user --> UC_Langue
@enduml