@startuml
!include .\\App.xaml.puml
!include .\\AppShell.xaml.puml
!include .\\GlobalUsing.puml
!include .\\MauiProgram.puml
!include .\\Model\Save.puml
!include .\\Services\Broker.puml
!include .\\Services\BusinessObserver.puml
!include .\\Services\EasySave.puml
!include .\\Services\Logger.puml
!include .\\Services\Parameters.puml
!include .\\Services\SaveConfiguration.puml
!include .\\Services\SaveManager.puml
!include .\\Services\SharedLocalizer.puml
!include .\\View\ChiffrementSettingsView.xaml.puml
!include .\\View\GeneralSettingsView.xaml.puml
!include .\\View\JournauxSettingsView.xaml.puml
!include .\\View\LanguesSettingsView.xaml.puml
!include .\\View\MainPage.xaml.puml
!include .\\View\ParametersPage.xaml.puml
!include .\\View\RunSavesPage.xaml.puml
!include .\\View\ThemesSettingsView.xaml.puml
!include .\\ViewModel\BaseViewModel.puml
!include .\\ViewModel\LanguesSettingsViewModel.puml
!include .\\ViewModel\MainPageViewModel.puml
!include .\\ViewModel\ParametersPageViewModel.puml
!include .\\ViewModel\RunSavesPageViewModel.puml
!include .\\Platforms\Android\MainActivity.puml
!include .\\Platforms\Android\MainApplication.puml
!include .\\Platforms\iOS\AppDelegate.puml
!include .\\Platforms\iOS\Program.puml
!include .\\Platforms\MacCatalyst\AppDelegate.puml
!include .\\Platforms\MacCatalyst\Program.puml
!include .\\Platforms\Tizen\Main.puml
!include .\\Platforms\Windows\App.xaml.puml
!include .\\obj\Debug\net8.0-android\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Debug\net8.0-android\EasySaveUI.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-android\EasySaveUI.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-android\__Microsoft.Android.Resource.Designer.puml
!include .\\obj\Debug\net8.0-android\android-arm\EasySaveUI.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-android\android-arm64\EasySaveUI.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-android\android-x64\EasySaveUI.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-android\android-x86\EasySaveUI.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-ios\iossimulator-x64\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Debug\net8.0-ios\iossimulator-x64\EasySaveUI.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-ios\iossimulator-x64\EasySaveUI.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-ios\iossimulator-x64\EasySaveUI.nfloat.g.puml
!include .\\obj\Debug\net8.0-maccatalyst\maccatalyst-x64\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Debug\net8.0-maccatalyst\maccatalyst-x64\EasySaveUI.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-maccatalyst\maccatalyst-x64\EasySaveUI.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-maccatalyst\maccatalyst-x64\EasySaveUI.nfloat.g.puml
!include .\\obj\Debug\net8.0-windows10.0.19041.0\win10-x64\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Debug\net8.0-windows10.0.19041.0\win10-x64\EasySaveUI.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows10.0.19041.0\win10-x64\EasySaveUI.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows10.0.19041.0\win10-x64\XamlTypeInfo.g.puml
!include .\\obj\Debug\net8.0-windows10.0.19041.0\win10-x64\Platforms\Windows\App.g.puml
!include .\\obj\Debug\net8.0-windows10.0.19041.0\win10-x64\Platforms\Windows\App.g.i.puml
@enduml
